from PyQt5 import QtCore, QtGui, QtWidgets
from hebb import train_hebb, predict
from hebb_XO import get_variant_sample


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 710)
        MainWindow.setStyleSheet("background-color: rgb(75, 75, 75);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 627, 627))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 1, 4, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_18.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_18.setText("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 3, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_20.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_20.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_20.setText("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 3, 4, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_19.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_19.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 3, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_17.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 3, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_15.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 2, 4, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_16.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_16.setText("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 3, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 1, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 1, 3, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_13.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 2, 2, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_1.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_1.setText("")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 0, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 2, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_11.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 2, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 4, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_14.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 2, 3, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_21.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_21.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_21.setText("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout.addWidget(self.pushButton_21, 4, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_22.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_22.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_22.setText("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout.addWidget(self.pushButton_22, 4, 1, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_23.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_23.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_23.setText("")
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout.addWidget(self.pushButton_23, 4, 2, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_24.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_24.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_24.setText("")
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout.addWidget(self.pushButton_24, 4, 3, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_25.setMinimumSize(QtCore.QSize(125, 125))
        self.pushButton_25.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_25.setText("")
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout.addWidget(self.pushButton_25, 4, 4, 1, 1)
        self.get_pred = QtWidgets.QPushButton(self.centralwidget)
        self.get_pred.setGeometry(QtCore.QRect(680, 250, 131, 41))
        self.get_pred.setStyleSheet("background-color: rgb(178, 178, 178);")
        self.get_pred.setObjectName("get_pred")
        self.lbl_out = QtWidgets.QLabel(self.centralwidget)
        self.lbl_out.setGeometry(QtCore.QRect(680, 320, 150, 51))
        self.lbl_out.setText("")
        self.lbl_out.setObjectName("lbl_out")
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(680, 600, 131, 41))
        self.reset.setStyleSheet("background-color: rgb(178, 178, 178);")
        self.reset.setObjectName("reset")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        model = self.get_model()

        self.lbl_out.setStyleSheet("color: white; font: 15pt Comic Sans MS;")

        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_1").clicked.connect(lambda x: self.toggle(1))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_2").clicked.connect(lambda x: self.toggle(2))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_3").clicked.connect(lambda x: self.toggle(3))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_4").clicked.connect(lambda x: self.toggle(4))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_5").clicked.connect(lambda x: self.toggle(5))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_6").clicked.connect(lambda x: self.toggle(6))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_7").clicked.connect(lambda x: self.toggle(7))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_8").clicked.connect(lambda x: self.toggle(8))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_9").clicked.connect(lambda x: self.toggle(9))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_10").clicked.connect(lambda x: self.toggle(10))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_11").clicked.connect(lambda x: self.toggle(11))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_12").clicked.connect(lambda x: self.toggle(12))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_13").clicked.connect(lambda x: self.toggle(13))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_14").clicked.connect(lambda x: self.toggle(14))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_15").clicked.connect(lambda x: self.toggle(15))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_16").clicked.connect(lambda x: self.toggle(16))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_17").clicked.connect(lambda x: self.toggle(17))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_18").clicked.connect(lambda x: self.toggle(18))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_19").clicked.connect(lambda x: self.toggle(19))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_20").clicked.connect(lambda x: self.toggle(20))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_21").clicked.connect(lambda x: self.toggle(21))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_22").clicked.connect(lambda x: self.toggle(22))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_23").clicked.connect(lambda x: self.toggle(23))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_24").clicked.connect(lambda x: self.toggle(24))
        self.gridLayoutWidget.findChild(QtWidgets.QPushButton, "pushButton_25").clicked.connect(lambda x: self.toggle(25))

        self.get_pred.clicked.connect(lambda x: self.action(model))
        self.reset.clicked.connect(self.reset_btns)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.get_pred.setText(_translate("MainWindow", "Predict"))
        self.reset.setText(_translate("MainWindow", "Reset"))

    def toggle(self, i):
        if self.gridLayoutWidget.findChild(QtWidgets.QPushButton, f"pushButton_{i}").styleSheet() == "background-color: rgb(255, 255, 255);":
            self.gridLayoutWidget.findChild(QtWidgets.QPushButton, f"pushButton_{i}").setStyleSheet("background-color: rgb(0, 0, 0);")
        else:
            self.gridLayoutWidget.findChild(QtWidgets.QPushButton, f"pushButton_{i}").setStyleSheet("background-color: rgb(255, 255, 255);")

    def get_model(self):
        X_indexes = [0, 4, 6, 8, 12, 16, 18, 20, 24]
        O_indexes = [1, 2, 3, 5, 9, 10, 14, 15, 19, 21, 22, 23]

        x_train = [get_variant_sample(X_indexes) for _ in range(20)] + [get_variant_sample(O_indexes) for _ in range(20)]
        y_train = [[1]] * 20 + [[-1]] * 20

        w, b = train_hebb(x_train, y_train)
        f_act = lambda x: 1 if x>=0 else -1

        print("Model trained and ready!")

        return (w, b, f_act)

    def action(self, model):
        test = []
        for i in range(1, 26):
            if self.gridLayoutWidget.findChild(QtWidgets.QPushButton, f"pushButton_{i}").styleSheet() == "background-color: rgb(0, 0, 0);":
                test.append(1)
            else:
                test.append(-1)
        
        w, b, f_act = model
        pred = "X" if predict(test, w, b, f_act)[0] == 1 else "O"

        self.lbl_out.setText(f"I think it's a {pred}!")

    def reset_btns(self):
        for i in range(1, 26):
            self.gridLayoutWidget.findChild(QtWidgets.QPushButton, f"pushButton_{i}").setStyleSheet("background-color: rgb(255, 255, 255);")

        self.lbl_out.setText("")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
